services:
  model:
    build:
      context: .
      dockerfile: ./compose/local/model/Dockerfile
    image: yolo_assessment
    container_name: yolo_assessment
    volumes:
      - ./app:/app
    env_file:
      - ./.envs/.model.env
    ports:
      - "8888:8888"
    command: ["/start"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '16gb'  # Aumenta el tamaño de la memoria compartida

