train: []

val:
  - ../init_baseChina_Drone/images/train
  - ../init_baseChina_MotorBike/images/train
  - ../init_baseCzech/images/train
  - ../init_baseIndia/images/train
  - ../init_baseJapan/images/train
  - ../init_baseNorway/images/train
  - ../init_baseUnited_States/images/train

nc: 4

names:
  0: 'D00'
  1: 'D10'
  2: 'D20'
  3: 'D40'