train:
  - init_baseChina_MotorBike/images/train
  - init_baseCzech/images/train
  - init_baseIndia/images/train
  - init_baseJapan/images/train
  - init_baseNorway/images/train
  - init_baseUnited_States/images/train

val:
  - init_baseChina_MotorBike/images/val
  - init_baseCzech/images/val
  - init_baseIndia/images/val
  - init_baseJapan/images/val
  - init_baseNorway/images/val
  - init_baseUnited_States/images/val

nc: 4

names:
  0: 'D00'
  1: 'D10'
  2: 'D20'
  3: 'D40'